spring:
    application:
        name: appointments-service

    datasource:
        password: 123456789
        username: app_user
        url: jdbc:mysql://localhost:3307/appointments_db?createDatabaseIfNotExist=True

    jpa:
        properties:
            hibernate:
                show-sql: true
                dialect: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
