spring:
    application:
        name: medical_records-service
    datasource:
        password: 123456789
        username: app_user
        url: jdbc:mysql://localhost:3310/medical_records_db?createDatabaseIfNotExist=True

    jpa:
        properties:
            hibernate:
                show-sql: true
                dialect: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
server:
    port: 8082
